FROM python:3.6.8

ARG HOST_UID

#RUN groupadd -r LA && \
#    useradd --no-log-init -r -m -u "$HOST_UID" -g LA LA

ENV LA_PATH="/home/LA"

#ENV PATH="${PATH}:${LA_PATH}/.local/bin"

RUN apt-get update && \
    apt-get install gettext -y

#USER LA

# Files of log file analyzer
COPY ./LogDig/LogDig.py ${LA_PATH}/LogDig/
COPY ./LogDig/LogDig.ini ${LA_PATH}/LogDig/
COPY ./LogDig/logdig_docker.sh ${LA_PATH}/LogDig/start.sh
COPY ./LogDig/LogFilesData.py ${LA_PATH}/LogDig/
COPY ./LogAna/logdig_analyze_template.py ${LA_PATH}/LogAna/
COPY ./LogCom/MapGEkml.py ${LA_PATH}/LogCom/
# Should be removed ?
COPY ./LogCom/LogGUI.py ${LA_PATH}/LogCom/

RUN pip install --upgrade pip
RUN pip3 install --upgrade pip

RUN pip install configparser
RUN pip install psutil
# Should be removed ?
RUN pip3 install PyQt5==5.10

WORKDIR ${LA_PATH}/LogDig/

CMD ${LA_PATH}/LogDig/start.sh
