FROM python:3.6.8

#ARG MY_PATH
ENV MY_PATH="/home/LA"

RUN apt-get update && \
    apt-get install gettext -y

#RUN apt install libgl1-mesa-glx

COPY ./LogDig/LogDig.py ${MY_PATH}/LogDig/
COPY ./LogDig/LogDig.ini ${MY_PATH}/LogDig/
COPY ./LogDig/logdig_docker.sh ${MY_PATH}/LogDig/start.sh
COPY ./LogDig/LogFilesData.py ${MY_PATH}/LogDig/

COPY ./LogAna/logdig_analyze_template.py ${MY_PATH}/LogAna/
COPY ./LogAna/ITS_4_back.py ${MY_PATH}/LogAna/

COPY ./LogCom/LogGUI.py ${MY_PATH}/LogCom/
COPY ./LogCom/MapGEkml.py ${MY_PATH}/LogCom/

RUN pip install --upgrade pip
RUN pip3 install --upgrade pip

RUN pip install configparser
RUN pip3 install PyQt5==5.10
RUN pip install psutil

WORKDIR ${MY_PATH}/LogDig/

#CMD start.sh

